# Per-tool implementation source lists for the compiler.
#
# Add dev/src/foo.cpp to the tools that use it by adding `foo` below. For
# subdirectories, use the path without `.cpp`, such as `parser/foo`.

FRONTEND_SOURCE_SET_TARGETS := abimangle pptoken posttoken ctrlexpr macro preproc recog nsdecl nsinit cy86 cppgm++ lowiropt lowir2cy86 lowir2native

FRONTEND_OBJ_BASENAMES_abimangle :=
FRONTEND_OBJ_BASENAMES_pptoken := pptoken_lib
FRONTEND_OBJ_BASENAMES_posttoken := pptoken_lib pp_token posttoken_support posttoken_pipeline
FRONTEND_OBJ_BASENAMES_ctrlexpr := pptoken_lib pp_token posttoken_support ctrlexpr_support
FRONTEND_OBJ_BASENAMES_macro := pptoken_lib pp_token posttoken_support posttoken_pipeline macro_support
FRONTEND_OBJ_BASENAMES_preproc := pptoken_lib pp_token posttoken_support posttoken_pipeline ctrlexpr_support macro_support preproc_support
FRONTEND_OBJ_BASENAMES_recog := pptoken_lib pp_token posttoken_support posttoken_pipeline ctrlexpr_support macro_support preproc_support recog_grammar recog_support
FRONTEND_OBJ_BASENAMES_nsdecl := pptoken_lib pp_token posttoken_support posttoken_pipeline ctrlexpr_support macro_support preproc_support nsdecl_model nsdecl_parser nsdecl_support
FRONTEND_OBJ_BASENAMES_nsinit := pptoken_lib pp_token posttoken_support posttoken_pipeline ctrlexpr_support macro_support preproc_support nsinit_model nsinit_eval nsinit_parser nsinit_image nsinit_support
FRONTEND_OBJ_BASENAMES_cy86 := pptoken_lib pp_token posttoken_support posttoken_pipeline ctrlexpr_support macro_support preproc_support cy86_model cy86_parser cy86_x86 cy86_support
FRONTEND_OBJ_BASENAMES_cppgm++ := pptoken_lib pp_token posttoken_support posttoken_pipeline ctrlexpr_support macro_support preproc_support pa10_support pa10_parser pa10_decls pa10_types pa10_expr pa11_model pa11_support pa11_parser pa11_emit pa12_support pa12_model pa12_decls pa12_decls_namespace pa12_decls_declare_one pa12_decl_variables pa12_decls_common pa12_decls_initializers pa12_decls_members pa12_static_assert pa12_types pa12_types_helpers pa12_types_declspec pa12_types_classes pa12_types_names pa12_types_declarators pa12_types_parameters pa12_templates pa12_templates_parameters pa12_templates_arguments pa12_templates_common pa12_templates_functions pa12_templates_function_deduction_support pa12_templates_function_abi pa12_templates_function_substitution pa12_templates_function_instantiation pa12_templates_function_deduce_type pa12_templates_function_deduce_call pa12_templates_function_deduce_target pa12_templates_instances pa12_templates_instance_keys pa12_templates_match_core pa12_templates_match_packs pa12_templates_partial_order pa12_templates_instance_values pa12_templates_instance_lookup pa12_templates_class_instances pa12_templates_member_instances pa12_templates_substitution_args pa12_templates_match_substitution pa12_templates_typename_resolution pa12_templates_type_substitution pa12_templates_variable_instances pa12_templates_lookup pa12_templates_validation pa12_templates_variables pa12_records pa12_statements pa12_constexpr pa12_constexpr_values pa12_expr pa12_expr_primary pa12_expr_call_helpers pa12_expr_packs pa12_expr_semantics pa12_expr_semantics_calls pa12_expr_semantics_constructors pa12_expr_nodes pa12_expr_ids pa12_expr_pointer pa12_names pa14_lowir pa14_lowir_call pa14_lowir_expr pa14_lowir_value_addr pa14_lowir_value_expr pa14_lowir_init pa14_lowir_object_init pa14_lowir_ctor_init pa14_lowir_globals pa14_lowir_support pa14_lowir_program pa14_lowir_inline_order pa14_lowir_emit pa14_lowir_program_io pa14_lowir_rtti
FRONTEND_OBJ_BASENAMES_lowiropt :=
FRONTEND_OBJ_BASENAMES_lowir2cy86 := lowir2cy86_model lowir2cy86_parser lowir2cy86_validate lowir2cy86_emit lowir2cy86_support
FRONTEND_OBJ_BASENAMES_lowir2native :=
