#pragma once
#include <map>
#include <memory>
#include <set>
#include <string>
#include <vector>
#include "pa10_parser_internal.h"
#include "pa11_internal.h"
#include "pa12_semantics.h"
#include "pa12_template_model.h"
using namespace std;
namespace pa12 {
namespace internal {
using pa10::internal::Token;
using pa11::Binding;
using pa11::BindingKind;
using pa11::Scope;
using pa11::ScopeKind;
using pa11::TypePtr;

enum class ValueCategory { LValue, PRValue, XValue };
enum class PtrKind { Pointer, LValueReference, RValueReference, MemberPointer };
enum class SuffixKind { Array, Function, Attribute };
struct Node
{
	string line;
	vector<Node> children;
	TypePtr type;
	ValueCategory category;
	Binding* binding;
	vector<Binding*> overloads;
	map<Binding*, vector<TemplateArgument> > explicit_template_arguments;
	Binding* direct_call;
	bool has_op;
	ETokenType op;
	string token_text;
	bool has_constant_value;
	uint64_t constant_value;
	string dependent_value_name;
	string dependent_value_owner_template_name;
	string dependent_value_member_name;
	bool dependent_value_negated;
	vector<pa11::TemplateInstanceArgument> dependent_value_owner_template_arguments;
	bool suppress_virtual_dispatch;
	bool virtual_dispatch;
	bool is_typeid_expression;
	bool is_dynamic_cast_expression;
	Node();
	explicit Node(const string& text);
};
struct QualifiedName
{
	Scope* qualifier;
	string name;
	string spelling;
	bool qualified;
	bool has_template_arguments;
	vector<TemplateArgument> template_arguments;
	QualifiedName();
};
struct Expr
{
	Node node;
	TypePtr type;
	ValueCategory category;
	Binding* binding;
	vector<Binding*> overloads;
	map<Binding*, vector<TemplateArgument> > explicit_template_arguments;
	bool pack_expansion;
	vector<Expr> pack;
	bool valid;
	bool null_pointer_constant;
	bool constant_expression;
	bool has_constant_value;
	uint64_t constant_value;
	bool builtin_constant_p;
	bool braced_init_list;
	bool copy_initialization;
	string dependent_value_name;
	string dependent_value_owner_template_name;
		string dependent_value_member_name;
		bool dependent_value_negated;
		vector<pa11::TemplateInstanceArgument> dependent_value_owner_template_arguments;
		size_t source_begin;
		size_t source_end;
		Expr();
	};
bool record_has_aggregate_blocking_constructor(TypePtr record);
bool string_literal_initializes_array(TypePtr type, const Expr& init, uint64_t* elements);
vector<Binding*> declared_instance_fields(TypePtr type);
struct DeclSpecs
{
	bool typedef_decl;
	bool constexpr_decl;
	bool static_decl;
	bool mutable_decl;
	bool friend_decl;
	bool extern_decl;
	bool thread_local_decl;
	bool auto_decl;
	bool virtual_decl;
	bool inline_decl;
	bool int128_decl;
	bool bitint_decl;
	bool no_unique_address_decl;
	uint64_t vector_size;
	unsigned cv;
	vector<ETokenType> builtin;
	TypePtr named_type;
	DeclSpecs();
};
struct PtrOp
{
	PtrKind kind;
	unsigned cv;
	TypePtr member_class;
	PtrOp(PtrKind k, unsigned flags);
	PtrOp(TypePtr class_type, unsigned flags);
};
struct ParameterInfo
{
	string name;
	TypePtr type;
	bool is_pack_expansion;
	string pack_name;
	string pack_expression_name;
	bool has_default;
	Expr default_value;
	ParameterInfo();
};
struct Suffix
{
	SuffixKind kind;
	bool unknown_bound;
	uint64_t bound;
	string array_bound_name;
	vector<ParameterInfo> parameters;
	bool variadic;
	unsigned function_cv;
	int ref_qualifier;
	bool noexcept_decl;
	bool dynamic_exception_spec;
	vector<TypePtr> dynamic_exception_types;
	bool override_decl;
	bool final_decl;
	TypePtr trailing_return;
	vector<string> abi_tags;
	string asm_label;
	uint64_t vector_size;
	explicit Suffix(SuffixKind k);
};
struct Declarator
{
	vector<PtrOp> prefix;
	vector<Suffix> suffixes;
	unique_ptr<Declarator> inner;
	bool has_name;
	QualifiedName name;
	string asm_label;
	Declarator();
};
struct PendingFunctionBody
{
	Binding* function;
	Node node;
	vector<ParameterInfo> parameters;
	size_t body_pos;
	bool constructor_body;
	bool prebuilt_node;
	TypePtr class_type;
	vector<Scope*> scopes;
	vector<Scope*> friend_class_scopes;
	vector<map<string, TypePtr> > type_substitutions;
	vector<map<string, TemplateArgument> > value_substitutions;
	vector<set<string> > pack_substitutions;
	PendingFunctionBody();
};
struct ConstructorInitializerParse
{
	string name;
	vector<TemplateArgument> template_arguments;
	bool have_template_arguments;
	Binding* field;
	Expr init;
	vector<Expr> parsed_args;
	size_t parsed_args_begin;
	size_t parsed_args_end;
	bool have_paren_init;
	bool have_init;
	bool pack_expansion;
	ConstructorInitializerParse()
		: have_template_arguments(false),
		  field(NULL),
		  parsed_args_begin(0),
		  parsed_args_end(0),
		  have_paren_init(false),
		  have_init(false),
		  pack_expansion(false)
	{
	}
};
struct Conversion
{
	bool viable;
	int rank;
	Expr expr;
	Conversion();
	Conversion(bool ok, int cost, const Expr& converted);
};
struct ConstexprValue
{
	bool valid;
	bool is_float;
	bool is_object;
	bool is_pointer;
	uint64_t int_value;
	long double float_value;
	Binding* pointer_binding;
	long long pointer_index;
	TypePtr object_type;
	map<Binding*, ConstexprValue> fields;
	vector<ConstexprValue> elements;
	ConstexprValue();
	static ConstexprValue integer(uint64_t value);
	static ConstexprValue floating(long double value);
	static ConstexprValue object(TypePtr type);
	static ConstexprValue pointer(Binding* binding, long long index);
};
bool constexpr_zero_value_for_type(TypePtr type, ConstexprValue& out);
bool constexpr_integral_compare(ETokenType op, TypePtr left_type, const ConstexprValue& lhs, const ConstexprValue& rhs, ConstexprValue& out);
bool constexpr_string_literal_element(const Node& node, const ConstexprValue& index, ConstexprValue& out);
	struct TemplateValidationState; struct TemplateArgumentCompleter; struct TypeSubstitutionEngine; struct FunctionTemplateInstantiationEngine;
class Parser
{
		friend struct TemplateValidationState; friend struct TemplateArgumentCompleter; friend struct TypeSubstitutionEngine; friend struct FunctionTemplateInstantiationEngine;
public:
	Parser(const string& srcfile, const Options& options);
	void parse_translation_unit();
	const Node& root() const;
	const vector<Node>& generated_nodes() const;
	const vector<Node>& extra_lowir_nodes() const;
	void complete_static_member_initializer_replays();
	bool demand_lowir_function_body(Binding* function);
	TypePtr substitute_type_for_template_match( TypePtr type, const map<string, TemplateArgument>& deduced);
	TypePtr expand_alias_template_for_match( TypePtr type, const map<string, TemplateArgument>& deduced);
	TypePtr resolve_dependent_typename_for_template_match(TypePtr type) const;
	bool template_value_argument_matches_for_template_match( TemplateDeclaration* specialization, const TemplateArgument& pattern, const TemplateArgument& actual, const map<string, TemplateArgument>& deduced);
	bool try_evaluate_template_value_argument_for_template_match( TemplateDeclaration* specialization, const TemplateArgument& pattern, const map<string, TemplateArgument>& deduced, TemplateArgument& out);
	bool try_evaluate_dependent_value_expression_argument( const TemplateArgument& arg, TemplateArgument& out);
	TemplateDeclaration* class_template_declaration_for_match( TypePtr type) const;
	private:
	bool hosted_library_function(Binding* binding) const;
	bool hosted_extern_template_class_function(Binding* binding) const;
	TemplateDeclaration* replacement_owner_template(TypePtr owner_record) const;
		vector<Token> tokens_;
		vector<Token> declaration_tokens_;
		size_t pos_;
	pa11::TranslationUnit tu_;
	vector<Scope*> scopes_;
	vector<TypePtr> function_returns_;
	vector<Binding*> active_functions_;
	TypePtr replay_function_type_override_;
	Scope* replay_function_type_override_owner_;
	string replay_function_type_override_name_;
	TemplateDeclaration* replay_function_template_declaration_;
	vector<TemplateArgument> replay_function_template_arguments_;
	set<Binding*> auto_return_functions_;
	map<Binding*, TypePtr> auto_return_patterns_;
	map<Binding*, TypePtr> auto_return_deduced_;
	int explicit_conversion_context_;
	vector<Scope*> active_friend_class_scopes_;
	vector<string> language_linkages_;
	vector<bool> class_private_access_;
	vector<bool> class_protected_access_;
	Node root_;
	vector<Node> generated_nodes_;
	vector<Node> extra_lowir_nodes_;
	bool hosted_compatibility_;
	int local_type_counter_;
	int range_for_counter_;
		bool force_new_function_binding_, defer_function_template_bodies_, force_function_template_body_instantiation_, suppress_implicit_template_base_init_, parsing_base_specifier_;
		bool validating_template_definition_, override_function_parameter_names_, replaying_dependent_decltype_, parsing_default_template_argument_, single_linkage_specification_declaration_;
	int defer_class_template_completion_depth_;
	int function_template_candidate_instantiation_depth_;
	int direct_template_call_depth_;
	int template_argument_expression_depth_;
	int constexpr_value_expression_depth_;
	int unevaluated_expression_depth_;
	int suppress_qualifier_template_member_instantiation_depth_;
	int short_circuit_static_member_demand_depth_;
			set<const void*> generated_default_ctors_, generated_copy_ctors_, generated_move_ctors_, generated_copy_assignments_, generated_move_assignments_, generated_dtors_;
		set<pair<const void*, size_t> > generated_aggregate_ctors_;
	map<Binding*, Node> default_member_initializers_;
	map<Binding*, Node> static_member_initializers_;
	map<Binding*, vector<Expr> > default_arguments_;
	map<Binding*, vector<string> > function_parameter_names_;
	vector<string> function_parameter_name_override_;
	set<Binding*> override_function_parameter_name_bindings_;
	set<Binding*> deleted_functions_;
	set<Binding*> provisional_initializer_bindings_;
	map<const void*, Scope*> enum_owner_scopes_;
	map<const void*, Scope*> record_owner_scopes_;
	map<Scope*, vector<Binding*> > class_friend_functions_;
	map<Scope*, vector<TypePtr> > class_friend_classes_;
	map<pair<Scope*, string>, vector<Binding*> > namespace_lookup_cache_;
	map<pair<pair<Scope*, string>, int>,
	    pair<size_t, vector<Binding*> > > unqualified_lookup_cache_;
	map<Scope*, vector<PendingFunctionBody> > pending_member_bodies_;
	map<Binding*, PendingFunctionBody> pending_function_bodies_;
	map<Scope*, vector<Scope*> > deferred_nested_member_body_scopes_;
	vector<Binding*> defaulted_move_assignments_;
	vector<unique_ptr<TemplateDeclaration> > template_declarations_;
	map<Scope*, map<string, TemplateDeclaration*> > class_templates_;
	map<Scope*, map<string, TemplateDeclaration*> > alias_templates_;
	map<Scope*, map<string, vector<TemplateDeclaration*> > > function_templates_;
	map<Scope*, map<string, vector<TemplateDeclaration*> > > variable_templates_;
	map<pair<TemplateDeclaration*, string>, TemplateDeclaration*> member_class_templates_;
		map<pair<TemplateDeclaration*, string>, vector<TemplateDeclaration*> > member_function_templates_;
		map<pair<TemplateDeclaration*, string>, vector<TemplateDeclaration*> > member_variable_templates_;
	map<Binding*, TemplateDeclaration*> function_template_placeholders_;
	map<Binding*, vector<TemplateArgument> > function_template_specialization_arguments_;
	set<Binding*> active_function_body_replays_;
	map<Binding*, TypePtr> lambda_closure_types_;
	map<Binding*, Binding*> lambda_call_operators_;
	map<Binding*, size_t> lambda_ordinals_;
	map<Binding*, size_t> lambda_counts_;
	map<Binding*, vector<TemplateParameterInfo> > lambda_template_parameters_;
	map<pair<Binding*, string>, Binding*> lambda_helper_specializations_;
	set<Binding*> lambda_requires_closure_object_;
	map<Binding*, vector<Node> > lambda_capture_initializers_;
	map<const void*, TemplateDeclaration*> record_template_declarations_;
	map<const void*, vector<TemplateArgument> > record_template_arguments_;
	map<pair<TemplateDeclaration*, string>, TypePtr> alias_template_specializations_;
		map<TemplateDeclaration*, map<string, Binding*> > variable_template_specializations_;
		set<pair<TemplateDeclaration*, string> > active_variable_template_specializations_;
		set<const void*> candidate_only_class_template_specializations_;
		set<const void*> demanded_class_template_specializations_;
		set<pair<const void*, bool> > active_member_function_template_records_;
		map<pair<const void*, bool>, size_t> completed_member_function_template_records_;
		size_t member_function_template_generation_;
		set<TemplateDeclaration*> class_templates_with_dependent_base_;
	set<const void*> record_dependent_base_lookup_skips_;
	vector<map<string, TypePtr> > template_type_substitutions_;
	vector<map<string, TemplateArgument> > template_value_substitutions_;
	vector<set<string> > template_type_parameter_packs_;
	vector<map<string, vector<Binding*> > > function_parameter_pack_substitutions_;
	vector<TemplateDeclaration*> completing_class_template_arguments_;
	vector<ActiveClassInstantiation> active_class_instantiations_;
	vector<TypePtr> active_class_virtual_completions_;
	mutable vector<string> active_dependent_type_substitution_keys_;
	mutable vector<string> active_template_argument_substitution_keys_;
	mutable vector<string> active_dependent_value_member_keys_;
	mutable vector<string> active_dependent_value_expression_keys_;
	mutable map<string, TemplateArgument> dependent_value_member_argument_cache_;
	mutable map<string, TemplateArgument> dependent_value_expression_argument_cache_;
		mutable set<string> dependent_value_expression_argument_fail_cache_;
		map<string, ConstexprValue> constexpr_call_result_cache_;
		vector<pair<TypePtr, TypePtr> > active_conversion_attempts_;
		vector<TypePtr> active_record_conversion_targets_;
	map<Binding*, Node> function_bodies_;
	Scope* current_scope() const;
	Scope* global_scope() const;
	TypePtr current_return_type() const;
	string current_language_linkage() const;
	bool at_eof() const;
	bool at_identifier() const;
	bool at_literal() const;
	bool at(ETokenType type) const;
	bool lookahead(ETokenType type, size_t offset) const;
	bool consume(ETokenType type);
	void expect(ETokenType type);
	void expect_eof();
	bool at_try_keyword() const;
	bool at_catch_keyword() const;
	bool consume_try_keyword();
	bool consume_catch_keyword();
	void expect_try_keyword();
	void expect_catch_keyword();
	string consume_identifier();
	string consume_literal();
	string consume_operator_function_name();
	TypePtr parse_conversion_type_id();
	string conversion_operator_name(TypePtr type) const;
	const Token& current() const;
	const Token& at_token(size_t index) const;
	void parse_declaration_into(Node& out);
	void parse_namespace_or_alias(Node& out);
	void parse_using_family(Node& out);
	void parse_static_assert_declaration();
		void parse_linkage_specification(Node& out);
			void parse_template_declaration();
			void parse_explicit_template_instantiation(bool extern_declaration);
		vector<TemplateParameterInfo> parse_template_parameter_clause();
		TemplateParameterInfo parse_template_parameter_info();
		void skip_template_parameter_default(TemplateParameterInfo& parameter);
					TemplateDeclaration* register_template_declaration( const vector<TemplateParameterInfo>& parameters, size_t decl_begin, size_t decl_end);
			void register_class_template(TemplateDeclaration* declaration);
			void register_alias_template(TemplateDeclaration* declaration);
			void register_function_template(TemplateDeclaration* declaration);
				void register_explicit_function_template_specialization( TemplateDeclaration* declaration, const QualifiedName& qname, TypePtr declared_type, size_t save_pos, const vector<map<string, TypePtr> >& save_subst, const vector<map<string, TemplateArgument> >& save_value_subst);
				bool register_conversion_function_template(TemplateDeclaration* declaration);
				bool register_constructor_template(TemplateDeclaration* declaration);
			bool register_dependent_nested_constructor_template( TemplateDeclaration* declaration);
			bool register_dependent_qualified_conversion_function_template( TemplateDeclaration* declaration);
			bool register_dependent_qualified_member_function_template( TemplateDeclaration* declaration);
			bool register_static_member_variable_template(TemplateDeclaration* declaration);
		size_t skip_template_declaration_body(size_t begin) const;
		bool find_template_type_substitution(const string& name, TypePtr& out) const;
			bool find_template_value_substitution(const string& name, TemplateArgument& out) const;
			bool active_type_parameter_pack(const string& name) const;
			bool function_parameter_type_pack_expansion_name(TypePtr pattern, string& name) const;
			bool type_substitution_hides_value_substitution( const string& name) const;
			bool parameter_pack_expansion_name(const string& name) const;
		bool find_function_parameter_pack_substitution(const string& name, vector<Binding*>& out) const;
		bool template_arguments_dependent( const vector<TemplateArgument>& arguments) const;
		bool active_class_instantiation_dependent() const;
			bool try_parse_template_template_argument(TemplateArgument& out);
			bool try_parse_dependent_qualified_non_type_template_argument( TemplateArgument& out);
				TemplateArgument parse_non_type_template_argument_expression();
				bool parse_template_argument_list(vector<TemplateArgument>& arguments);
				vector<TemplateArgument> expand_template_argument_pack(const TemplateArgument& argument) const;
				void append_completed_template_pack_argument( TemplateDeclaration* declaration, size_t parameter_index, TypePtr parameter_type, const vector<TemplateArgument>& explicit_expanded, size_t& explicit_index, vector<TemplateArgument>& out);
				TemplateArgument parse_non_type_default_template_argument(const TemplateParameterInfo& parameter, const vector<TemplateArgument>& completed_args);
				TemplateArgument parse_default_template_argument( TemplateDeclaration* declaration, size_t parameter_index, const vector<TemplateArgument>& completed_args);
			TemplateArgument convert_completed_non_type_template_argument( TemplateArgument argument, TypePtr parameter_type);
			vector<TemplateArgument> complete_template_arguments( TemplateDeclaration* declaration, const vector<TemplateArgument>& explicit_arguments);
		string template_argument_key( const vector<TemplateArgument>& arguments) const;
		string template_specialization_name( TemplateDeclaration* declaration, const vector<TemplateArgument>& arguments) const;
			TemplateDeclaration* find_class_template(Scope* scope, const string& name);
			TemplateDeclaration* find_alias_template(Scope* scope, const string& name);
			bool resolve_template_name_spelling(const string& spelling, Scope*& qualifier, string& name);
			TypePtr instantiate_alias_template(TemplateDeclaration* declaration, const vector<TemplateArgument>& arguments);
			TypePtr instantiate_class_template(TemplateDeclaration* declaration, const vector<TemplateArgument>& arguments);
	TypePtr make_std_initializer_list_type(TypePtr element);
	bool is_std_initializer_list_type(TypePtr type, TypePtr* element = NULL) const;
	void normalize_std_initializer_list_type(TypePtr type);
	Expr make_initializer_list_expr(const Expr& init, TypePtr target);
	void complete_template_record(TypePtr type);
	void mark_template_specialization_demanded(TypePtr type);
	void mark_template_argument_demanded(const TemplateArgument& argument);
	void complete_member_class_template_record(Binding* binding);
				void instantiate_member_function_templates(TypePtr type, bool object_root = false);
				void make_concrete_outer_substitutions(TemplateDeclaration* declaration, TemplateDeclaration* owner_declaration, const vector<TemplateArgument>& owner_arguments, const map<string, TypePtr>& owner_type_subst, const map<string, TemplateArgument>& owner_value_subst, vector<map<string, TypePtr> >& type_substitutions, vector<map<string, TemplateArgument> >& value_substitutions);
				void add_member_function_template(std::vector<TemplateDeclaration*>& members, TemplateDeclaration* declaration);
	void instantiate_member_variable_templates(TypePtr type);
			void validate_class_template_definition(TemplateDeclaration* declaration);
			void validate_function_template_definition(TemplateDeclaration* declaration);
			bool type_is_template_dependent(TypePtr type) const;
				TypePtr substitute_template_type(TypePtr type) const;
				TypePtr substitute_template_type_in_scope(TypePtr type, Scope* scope) const;
					TypePtr substitute_function_template_type( TemplateDeclaration* declaration, TypePtr type) const;
				TypePtr resolve_dependent_typename_type(TypePtr type) const;
				TypePtr hosted_hash_node_value_type(TypePtr node_type) const; TypePtr hosted_lookup_type_member(Scope* scope, const string& name) const;
				TypePtr hosted_allocator_member_type(TypePtr allocator_type, const string& member_name) const; TypePtr hosted_allocator_value_type(TypePtr allocator_type) const; TypePtr hosted_get_value_type_from_context() const;
				TypePtr hosted_allocator_rebind_value_type() const; TypePtr hosted_active_template_parameter_type(const string& parameter_name) const; TypePtr hosted_rebind_allocator_type(TypePtr allocator_type, TypePtr rebound_type) const;
				TypePtr hosted_allocator_rebind_member_type(const string& member_name) const; TypePtr hosted_bool_constant_type(bool value) const; bool hosted_invoke_result_call_types(TypePtr invoke_result, vector<TypePtr>& call_types) const;
				TypePtr hosted_call_result_type(const vector<TypePtr>& call_types) const; TypePtr hosted_invoke_result_type(TypePtr invoke_result) const; TypePtr resolve_hosted_invoke_call_type(TypePtr call_type) const;
				bool try_resolve_type_pack_element( const vector<TemplateArgument>& arguments, TypePtr& out);
			bool dependent_typename_template_argument_list( TypePtr type, size_t& index, vector<TemplateArgument>& arguments) const;
			TemplateArgument template_argument_from_instance_argument( const pa11::TemplateInstanceArgument& argument) const;
			TemplateArgument substitute_template_argument( const TemplateArgument& arg) const;
			TypePtr hosted_dependent_value_traits_record(const string& owner_parameter) const; bool resolve_hosted_dependent_value_member_argument(const TemplateArgument& arg, TemplateArgument& out) const;
			TypePtr make_integer_sequence_type( const vector<TemplateArgument>& arguments);
		bool resolve_dependent_value_member_argument( const TemplateArgument& arg, TemplateArgument& out) const;
		TypePtr substitute_template_type_parameter(TypePtr type, const string& name, TypePtr replacement) const;
		TemplateArgument substitute_template_argument_type_parameter( const TemplateArgument& arg, const string& name, TypePtr replacement) const;
					vector<Binding*> instantiate_explicit_function_templates(const QualifiedName& name);
					void select_variable_template_specialization( TemplateDeclaration* declaration, const vector<TemplateArgument>& full_args, size_t explicit_arg_count, TemplateDeclaration*& selected_declaration, vector<TemplateArgument>& selected_args);
				Binding* instantiate_variable_template(TemplateDeclaration* declaration, const vector<TemplateArgument>& arguments);
				vector<TemplateDeclaration*> find_function_templates(const QualifiedName& name);
			bool visible_function_template_name(const QualifiedName& name);
			bool visible_variable_template_name(const QualifiedName& name);
				bool record_skips_dependent_base_unqualified_lookup( TypePtr record) const;
			bool constructor_name_matches_scope(Scope* class_scope, const string& name) const;
			Binding* instantiate_function_template( TemplateDeclaration* declaration, const vector<TemplateArgument>& arguments);
			bool deduce_function_template_arguments(TemplateDeclaration* declaration, const vector<Expr>& args, const vector<TemplateArgument>& explicit_arguments, vector<TemplateArgument>& out);
			bool deduce_function_template_target_type(TemplateDeclaration* declaration, TypePtr target, const vector<TemplateArgument>& explicit_arguments, vector<TemplateArgument>& out);
			bool deduce_template_type(TypePtr pattern, TypePtr argument, map<string, TypePtr>& deduced, const map<string, TypePtr>* fixed, map<string, TemplateArgument>* deduced_arguments = NULL) const;
			bool deduce_explicit_function_template_arguments(TemplateDeclaration* declaration, const vector<TemplateArgument>& explicit_arguments, map<string, TypePtr>& deduced, map<string, TypePtr>& fixed, map<string, vector<TemplateArgument> >& deduced_packs, map<string, TemplateArgument>& fixed_arguments, vector<TemplateArgument>& out, bool& complete);
			bool deduce_explicit_pack_template_argument(const TemplateParameterInfo& parameter, const vector<TemplateArgument>& explicit_arguments, size_t& explicit_index, map<string, vector<TemplateArgument> >& deduced_packs, map<string, TemplateArgument>& fixed_arguments) const;
			bool deduce_explicit_single_template_argument(const TemplateParameterInfo& parameter, const TemplateArgument& explicit_arg, map<string, TypePtr>& deduced, map<string, TypePtr>& fixed, map<string, TemplateArgument>& fixed_arguments) const;
			bool deduce_function_template_call_parameters(TemplateDeclaration* declaration, TypePtr fn, const vector<Expr>& args, map<string, TypePtr>& deduced, map<string, TypePtr>& fixed, map<string, vector<TemplateArgument> >& deduced_packs, map<string, TemplateArgument>& fixed_arguments, size_t& arg_index) const;
			bool deduce_function_template_parameter_pack(TemplateDeclaration* declaration, TypePtr pattern, const string& pack_name, size_t remaining_function_parameters, const vector<Expr>& args, map<string, TypePtr>& deduced, map<string, TypePtr>& fixed, map<string, vector<TemplateArgument> >& deduced_packs, map<string, TemplateArgument>& fixed_arguments, size_t& arg_index) const;
			bool deduce_function_template_overload_argument(TypePtr pattern, const Expr& actual, map<string, TypePtr>& deduced, map<string, TypePtr>& fixed, map<string, TemplateArgument>& fixed_arguments) const;
			bool deduce_single_overload_template_argument(TypePtr pattern, const Expr& actual, const vector<TypePtr>& overload_types, map<string, TypePtr>& deduced, map<string, TypePtr>& fixed, map<string, TemplateArgument>& fixed_arguments) const;
			bool deduce_overload_set_template_argument(TypePtr pattern, const Expr& actual, map<string, TypePtr>& deduced, map<string, TypePtr>& fixed, map<string, TemplateArgument>& fixed_arguments) const;
			bool deduce_initializer_list_template_argument(TypePtr pattern, const Expr& actual, map<string, TypePtr>& deduced, const map<string, TypePtr>& fixed, map<string, TemplateArgument>& fixed_arguments) const;
			bool deduce_regular_template_call_argument(TypePtr pattern, const Expr& actual, map<string, TypePtr>& deduced, map<string, TypePtr>& fixed, map<string, TemplateArgument>& fixed_arguments) const;
			bool append_deduced_function_template_argument(TemplateDeclaration* declaration, const TemplateParameterInfo& parameter, size_t parameter_index, map<string, TypePtr>& deduced, map<string, vector<TemplateArgument> >& deduced_packs, map<string, TemplateArgument>& fixed_arguments, bool& saw_template_parameter_pack, vector<TemplateArgument>& explicit_args);
			bool finish_deduced_function_template_arguments(TemplateDeclaration* declaration, map<string, TypePtr>& deduced, map<string, vector<TemplateArgument> >& deduced_packs, map<string, TemplateArgument>& fixed_arguments, vector<TemplateArgument>& out);
		void parse_simple_or_function_declaration(Node& out, bool emit_node);
		bool parse_structured_binding_declaration(const DeclSpecs& specs,
		                                          Node& out,
		                                          bool emit_node);
		bool parse_qualified_constructor_definition(Node& out, bool emit_node, bool inline_spec = false, bool constexpr_spec = false);
		bool parse_qualified_conversion_definition(Node& out, bool emit_node);
			bool parse_constructor_like_member(bool explicit_ctor = false, bool constexpr_ctor = false);
			bool parse_conversion_function_member(bool explicit_conv = false, bool constexpr_conv = false);
		bool parse_destructor_like_member();
		bool parse_friend_declaration();
		void parse_class_body(Scope* class_scope, bool default_private);
		bool parse_trailing_declarator_initializer(TypePtr declared_type,
		                                           Expr& init);
		DeclSpecs parse_decl_specifier_seq(bool type_id_context);
		bool try_parse_builtin_va_list_decl_spec(DeclSpecs& specs,
		                                         bool& saw_non_cv_type);
		bool parse_decl_storage_specifier(DeclSpecs& specs, bool type_id_context, bool& saw_any);
		bool parse_decl_type_specifier(DeclSpecs& specs, bool type_id_context, bool& saw_any, bool& saw_non_cv_type);
		TypePtr type_from_decl_specs(const DeclSpecs& specs);
		TypePtr parse_type_id();
		TypePtr parse_decltype_specifier();
		TypePtr parse_decltype_sizeof_operand();
		bool try_parse_decltype_named_operand(size_t save, TypePtr& out);
		bool decltype_concrete_substitution_context() const;
		TypePtr parse_dependent_decltype_fallback(size_t save);
		void replay_decltype_substitution(Expr& expr);
		bool decltype_mentions_active_template_parameter(size_t begin, size_t end) const;
		TypePtr finish_decltype_expression_type(size_t save, Expr& expr);
	TypePtr parse_class_specifier();
	TypePtr parse_enum_specifier();
	EFundamentalType parse_enum_underlying_type();
	bool try_parse_type_name(TypePtr& out);
	bool starts_declaration();
	bool starts_attribute() const;
	void skip_attributes(bool* no_unique_address = NULL);
	bool at_gnu_asm() const;
	string parse_gnu_asm_label();
	void skip_gnu_asm();
	bool starts_class_key() const;
	bool starts_ptr_operator() const;
	bool starts_declarator() const;
	bool starts_abstract_declarator() const;
	bool starts_parenthesized_abstract_declarator() const;
	bool at_simple_ignored_specifier() const;
	bool at_simple_cv() const;
	bool at_simple_builtin() const;
	unsigned consume_cv_flag();
	Declarator parse_declarator(bool abstract_allowed);
	Declarator parse_abstract_declarator();
		void parse_noptr_declarator_root(Declarator& declarator, bool abstract_allowed);
	void parse_ptr_prefix(vector<PtrOp>& ops);
	void parse_suffixes(vector<Suffix>& suffixes,
	                    bool qualified_declarator = false);
	Suffix parse_array_suffix();
	Suffix parse_function_suffix();
	void parse_function_suffix_tail(Suffix& suffix);
	bool parse_gnu_attribute_suffix(Suffix& suffix);
		void parse_parameter_clause(vector<ParameterInfo>& parameters, bool& variadic);
	ParameterInfo parse_parameter_declaration();
	vector<ParameterInfo> expand_parameter_pack( const ParameterInfo& parameter) const;
	TypePtr apply_declarator(const Declarator& declarator, TypePtr base);
	TypePtr apply_ptr_ops(TypePtr type, const vector<PtrOp>& ops);
	TypePtr apply_suffixes(TypePtr type, const vector<Suffix>& suffixes);
	const QualifiedName& declarator_name(const Declarator& declarator) const;
	bool declarator_has_name(const Declarator& declarator) const;
	const Suffix* declarator_function_suffix(const Declarator& declarator) const;
	string declarator_asm_label(const Declarator& declarator) const;
			void parse_function_body(Binding* function,
			                         const Declarator& declarator,
			                         Node& function_node,
			                         bool inline_definition_spec = false);
			void parse_function_body_from_parameters(
				Binding* function,
				const vector<ParameterInfo>& parameters,
				Node& function_node,
				bool inline_definition_spec = false);
			void parse_constructor_body_from_parameters(Binding* function, TypePtr class_type, const vector<ParameterInfo>& parameters, Node& function_node);
			Binding* add_constructor_this_parameter(Node& fn, Scope* function_scope, const string& function_name, TypePtr this_type);
			map<string, vector<Binding*> > bind_constructor_body_parameters(Binding* function, const vector<ParameterInfo>& parameters, Scope* function_scope, Node& fn);
			void bind_constructor_signature_parameters(Node& fn, Scope* function_scope, const vector<ParameterInfo>& parameters, const vector<size_t>& signature_parameter_indices);
			TypePtr constructor_initializer_target(Scope* class_scope, TypePtr class_type, TypePtr direct_base, const ConstructorInitializerParse& clause, bool& target_is_base);
			ConstructorInitializerParse parse_constructor_initializer_clause(Scope* class_scope, TypePtr class_type, TypePtr direct_base);
			vector<TypePtr> constructor_initializer_matching_bases(Scope* class_scope, const vector<TypePtr>& direct_bases, const ConstructorInitializerParse& clause);
			vector<Expr> expand_constructor_initializer_pack(const ConstructorInitializerParse& clause, size_t match_count);
			void append_constructor_base_initializer_actions(const ConstructorInitializerParse& clause, const vector<TypePtr>& matching_bases, const vector<Expr>& expanded_inits, vector<Node>& explicit_base_actions);
			void apply_constructor_initializer_clause(Scope* class_scope, TypePtr class_type, Binding* this_binding, const vector<TypePtr>& direct_bases, const ConstructorInitializerParse& clause, Node& body, map<Binding*, Node>& explicit_member_initializers, vector<Node>& explicit_base_actions, bool& delegating);
			bool parse_constructor_initializer_list(Scope* class_scope, TypePtr class_type, Binding* this_binding, Node& body, map<Binding*, Node>& explicit_member_initializers, vector<Node>& explicit_base_actions, const vector<TypePtr>& direct_bases);
			void append_constructor_member_init_actions(TypePtr class_type, Binding* this_binding, const map<Binding*, Node>& explicit_member_initializers, Node& body);
			void append_constructor_compound_body(Node& body, bool function_try_block);
			bool parse_qualified_constructor_header(size_t save, Scope*& class_scope, TypePtr& class_type, vector<ParameterInfo>& parameters, bool& variadic, Suffix& suffix, bool& defaulted, vector<size_t>& signature_parameter_indices, TypePtr& fn_type);
			Binding* prepare_qualified_constructor_binding(Scope* class_scope, TypePtr class_type, vector<ParameterInfo>& parameters, const vector<size_t>& signature_parameter_indices, TypePtr fn_type, const Suffix& suffix, bool defaulted, bool inline_spec, bool constexpr_spec, bool& qualified_inline_object_root);
			bool defer_qualified_constructor_definition(Scope* class_scope, TypePtr class_type, Binding* ctor, const vector<ParameterInfo>& parameters, const Node& fn, bool emit_node, bool qualified_inline_object_root, Node& out);
			void parse_immediate_qualified_constructor_definition(Scope* class_scope, TypePtr class_type, Binding* ctor, const vector<ParameterInfo>& parameters, const vector<size_t>& signature_parameter_indices, TypePtr fn_type, bool defaulted, Node& fn);
		void remember_function_body(Binding* function, const Node& function_node);
	void enqueue_pending_member_body(Scope* class_scope, PendingFunctionBody pending);
	void enqueue_pending_function_body(PendingFunctionBody pending);
	void push_pending_owner_template_substitutions( const PendingFunctionBody& pending);
	void push_pending_function_template_substitutions( const PendingFunctionBody& pending);
	bool parse_pending_member_body_now(const PendingFunctionBody& pending,
	                                   bool force_hosted_body = false);
			bool parse_pending_function_body(Binding* function);
			bool parse_pending_member_body(Binding* function);
			bool defer_hosted_function_body(Binding* function) const;
			bool mark_hosted_stream_insertion_extern_template(Binding* function) const;
			void ensure_function_body_extra_node(Binding* function,
			                                     bool force_hosted_body = false);
		void parse_pending_member_bodies(Scope* class_scope);
	void parse_deferred_nested_member_bodies(Scope* class_scope);
	Node parse_compound_statement();
	Node parse_block_item();
	Node parse_statement();
	void skip_constexpr_if_statement();
	Node parse_if_statement();
	Node parse_switch_statement();
	Node parse_while_statement();
		Node parse_do_statement();
		Node parse_for_statement();
		Node parse_range_for_statement();
		Node parse_try_statement();
		Node parse_jump_statement();
		Expr convert_return_expression(Expr expr, TypePtr result);
			Expr convert_aggregate_return_expression(Expr expr, TypePtr result, TypePtr result_record);
			Expr convert_record_constructor_return_expression(Expr expr, TypePtr result);
			void validate_same_record_return_expression(const Expr& expr, TypePtr result);
		Node parse_labeled_statement();
		Node parse_expression_statement();
		Node parse_condition(TypePtr target);
	Expr parse_expression();
	Expr parse_assignment_expression();
	Expr parse_conditional_expression();
	Expr parse_binary_expression(int min_prec);
	Expr parse_unary_expression();
		Expr parse_noexcept_expression();
		Expr parse_is_constructible_expression();
		Expr parse_builtin_type_trait_expression();
		void parse_type_trait_operand_list(const string& name, vector<TypePtr>& types, bool& dependent, string& spelling);
		Expr make_dependent_type_trait_expr(const string& spelling);
		bool evaluate_builtin_type_relation_trait(const string& name, const vector<TypePtr>& types, bool& value);
		bool evaluate_unary_builtin_type_trait(const string& name, TypePtr type, bool& value);
		bool evaluate_builtin_type_trait(const string& name, const vector<TypePtr>& types);
		bool at_builtin_type_trait_expression() const;
	Expr parse_builtin_integral_type_trait_expression();
	bool at_builtin_integral_type_trait_expression() const;
	bool is_constructible_type_trait(const vector<TypePtr>& types);
	bool is_nothrow_constructible_type_trait(const vector<TypePtr>& types);
	bool try_make_invocable_type_trait_call(const vector<TypePtr>& types,
	                                        Expr& call);
	bool is_invocable_type_trait(const vector<TypePtr>& types,
	                             bool require_noexcept);
	bool is_invocable_r_type_trait(const vector<TypePtr>& types,
	                               bool require_noexcept);
		Expr parse_postfix_expression();
		Expr parse_direct_call_postfix_expression();
		Expr make_direct_named_call_expr(const QualifiedName& name, const vector<Expr>& args);
		void add_adl_call_candidates(const QualifiedName& name, const vector<Expr>& args, Expr& callee);
		bool make_dependent_or_missing_direct_call(const QualifiedName& name, const vector<Expr>& args, Expr& out);
		Expr parse_postfix_suffixes(Expr expr);
		Expr parse_member_access_postfix_suffix(Expr expr, const string& op);
		Expr make_pseudo_destructor_suffix(Expr expr, const string& op);
		void reject_missing_template_disambiguator(const Expr& expr, bool template_disambiguator);
		Expr make_qualified_member_suffix_expr(Expr object, const QualifiedName& member_name, const string& op);
		void attach_explicit_member_template_arguments(Expr& expr, const QualifiedName& member_name);
		Expr parse_primary_expression();
	Expr parse_lambda_expression();
		bool is_lambda_helper_expr(const Expr& expr) const;
		Expr lambda_closure_expr(const Expr& expr);
		bool call_has_function_template_candidate(const Expr& callee) const;
		void materialize_template_lambda_arguments(
			const Expr& callee,
			vector<Expr>& args);
	Expr parse_new_expression();
	Expr parse_delete_expression();
	Expr parse_literal_expression();
	Expr parse_cast_expression();
	Expr parse_type_trait_expression(ETokenType keyword);
		Expr parse_c_style_cast_or_parenthesized();
		Expr parse_functional_cast(TypePtr target);
		Expr parse_braced_init_list();
		bool try_parse_static_member_pack_expansion(vector<Expr>& out);
		vector<Expr> parse_argument_list();
		Binding* declare_one(const DeclSpecs& specs, TypePtr base, const Declarator& declarator, const Expr* init, bool function_definition, Node& out);
			Binding* declare_function_entity(const DeclSpecs& specs, Scope* target, const string& name, TypePtr type, const Declarator& declarator, bool function_definition, bool nonstatic_member_function, bool hidden_friend, Node& out);
			Binding* finish_variable_declaration(const DeclSpecs& specs, Scope* target, Binding* variable, const QualifiedName& qname, TypePtr type, const Expr* init, Node& out);
				void complete_class_virtuals(TypePtr type);
			Binding* find_overridden_virtual(TypePtr record, Binding* function) const;
			void apply_variable_initializer(const DeclSpecs& specs, Scope* target, Binding* variable, TypePtr type, const Expr* init, Node& var);
				void apply_braced_variable_initializer(Scope* target, Binding* variable, TypePtr type, const Expr& init, Node& var);
				void apply_record_variable_initializer(Scope* target, Binding* variable, TypePtr type, const Expr& init, Node& var);
				void demand_empty_record_conversion_bodies(TypePtr src_record, TypePtr dst_record, const Node& conversion_node);
				bool record_copy_move_initializer_blocked(TypePtr dst_record, ValueCategory init_category) const;
				void apply_scalar_variable_initializer(const DeclSpecs& specs, Scope* target, Binding* variable, TypePtr type, const Expr& init, Node& var);
			void validate_record_copy_initialization(TypePtr type, const Expr& init);
			void validate_aggregate_braced_initialization(TypePtr record);
		bool parse_qualified_destructor_definition(Node& out, bool emit_node);
		Binding* add_alias(Scope* scope, const string& name, TypePtr type);
		Binding* add_function_binding(Scope* scope, const string& name, TypePtr type, bool hidden_friend);
		void add_friend_function(Scope* class_scope, Binding* function);
		void add_friend_class(Scope* class_scope, TypePtr type);
	Binding* add_value(Scope* scope, BindingKind kind, const string& name, TypePtr type);
	TypePtr add_record(Scope* scope, const string& name, const string& tag, bool complete, Scope* class_scope);
	TypePtr add_enum(Scope* scope, const string& name, bool scoped, EFundamentalType underlying, bool complete, bool create_scope);
	void inject_anonymous_union_members(Scope* class_scope, Binding* storage);
			Binding* ensure_default_constructor(TypePtr type, bool force_trivial = false);
			void discard_implicit_default_constructor(TypePtr type,
			                                          Binding* keep = NULL);
		bool aggregate_omitted_field_requires_argument(TypePtr type);
		void complete_aggregate_constructor_args(TypePtr type,
		                                         vector<Expr>& args);
		Binding* ensure_aggregate_constructor(TypePtr type, size_t arg_count);
		void ensure_aggregate_constructors_for_init(TypePtr type, const Node& init);
	Binding* ensure_copy_move_constructor(TypePtr type, bool move);
	bool copy_move_constructor_available(TypePtr type, bool move);
	bool default_constructor_is_nothrow(TypePtr type);
	bool copy_move_constructor_is_nothrow(TypePtr type, bool move);
	Binding* ensure_copy_move_assignment(TypePtr type, bool move);
	bool copy_move_assignment_available(TypePtr type, bool move);
	Binding* ensure_default_destructor(TypePtr type, bool force_trivial = false);
	Binding* find_default_constructor(TypePtr type) const;
		TypePtr make_member_function_type(Scope* class_scope, TypePtr type);
			Node make_member_init_action(Binding* field, const Node* init,
			                             Binding* this_binding = NULL);
		Node make_base_init_action(TypePtr base, const Node* init);
		void append_constructor_base_init_actions(
			TypePtr class_type,
			const vector<TypePtr>& direct_bases,
			const vector<Node>& explicit_base_actions,
			Node& body);
		Node make_member_fini_action(Binding* field, Binding* dtor = NULL);
		Node make_base_fini_action(TypePtr base, Binding* dtor = NULL);
		void mark_suppressed_generated_constructor_dependencies(Binding* ctor);
		bool initializer_names_direct_base(Scope* class_scope, TypePtr direct_base, const string& name, const vector<TemplateArgument>* template_arguments = NULL);
		Node default_constructor_action(Binding* variable, bool force_trivial = false);
	void resolve_pending_member_initializers(Scope* class_scope, Node& node);
	QualifiedName parse_id_expression_name();
	Scope* parse_nested_name_specifier(string* spelling);
	Scope* parse_qualified_namespace_specifier();
	Scope* resolve_qualifier(Binding* binding);
	vector<Binding*> resolve_name_set(const QualifiedName& name, int mask);
	Binding* resolve_single_name(const QualifiedName& name, int mask);
	vector<Binding*> lookup_unqualified_set(Scope* start, const string& name, int mask);
	vector<Binding*> lookup_qualified_set(Scope* scope, const string& name, int mask);
	Scope* nearest_namespace_scope(Scope* scope) const;
	Conversion convert_to(const Expr& expr, TypePtr target);
		Conversion convert_reference(const Expr& expr, TypePtr target);
		Conversion try_reference_conversion_functions(const Expr& selected, TypePtr target);
		bool conversion_function_template_candidate(Binding* op) const;
			Binding* instantiate_conversion_function_template_candidate(Binding* op, TypePtr target);
				Conversion convert_value(const Expr& expr, TypePtr target);
				Expr select_overload_expr(const Expr& expr, TypePtr target);
				TemplateDeclaration* replacement_member_function_template_definition(TemplateDeclaration* declaration, TypePtr owner_record, TemplateDeclaration* owner_template, bool declaration_has_body);
				TemplateDeclaration* replacement_free_function_template_definition(TemplateDeclaration* declaration, bool declaration_has_body);
				TemplateDeclaration* replacement_function_template_definition(TemplateDeclaration* declaration);
			Binding* instantiate_target_overload_candidate(Binding* candidate, TypePtr wanted, const map<Binding*, vector<TemplateArgument> >& explicit_template_arguments);
			bool make_call_pack_expr(const Expr& callee, const vector<Expr>& args, Expr& out);
		bool make_template_id_callee_pack_expr(const Expr& callee, Expr& out);
		bool try_expand_expression_pack_pattern(size_t begin, size_t end, vector<Expr>& out);
		void substitute_lambda_helper_node_types(
			Node& node,
			const map<string, TypePtr>& substitutions,
			const map<Binding*, Binding*>& replacements) const;
			Binding* instantiate_lambda_helper_call(Binding* helper,
			                                        const vector<Expr>& args,
			                                        vector<Expr>& converted);
			bool deduce_lambda_helper_substitutions(Binding* helper, const vector<Expr>& args, vector<TemplateArgument>& full_args, map<string, TypePtr>& substitutions, string& key);
			void materialize_lambda_helper_parameters(Binding* helper, Binding* binding, TypePtr concrete_type, Node& fn, Scope* function_scope, map<Binding*, Binding*>& replacements);
			void substitute_lambda_helper_defaults(Binding* helper, Binding* binding, const map<string, TypePtr>& substitutions);
	Binding* resolve_call_candidate(const vector<Binding*>& overloads, const vector<Expr>& args, const map<Binding*, vector<TemplateArgument> >& explicit_template_arguments, vector<Expr>& converted);
		bool call_candidate_has_arguments(Binding* fn, size_t arg_count) const;
		bool convert_call_candidate_arguments(Binding* fn, const vector<Expr>& args, vector<Expr>& conv_args, vector<int>& ranks, int& object_rank);
		bool instantiate_function_default_argument(Binding* fn, const Expr& default_arg, TypePtr parameter_type, Expr& out);
		Binding* instantiate_template_call_candidate(Binding* fn, const map<Binding*, vector<TemplateArgument> >& explicit_template_arguments, const vector<Expr>& args);
		void prepare_constructor_template_candidates(TypePtr record, const vector<Expr>& args);
		Binding* instantiate_constructor_template_candidate(TypePtr record, Binding* ctor, const vector<Expr>& args);
		Binding* find_duplicate_constructor_candidate(Binding* ctor, const vector<Binding*>& considered);
		bool should_replace_duplicate_constructor(Binding* ctor, Binding* duplicate);
		bool constructor_accepts_argument_count(Binding* ctor, size_t arg_count) const;
		bool convert_constructor_candidate_arguments(Binding* ctor, const vector<Expr>& args, vector<Expr>& conv_args, vector<int>& ranks);
		bool constructor_candidate_better(Binding* ctor, Binding* best, const vector<int>& ranks, const vector<int>& best_ranks, const vector<Expr>& template_order_args);
		bool constructor_candidate_ambiguous(Binding* ctor, Binding* best, const vector<int>& ranks, const vector<int>& best_ranks, const vector<Expr>& template_order_args);
		void select_constructor_candidate(TypePtr record, const vector<Expr>& args, bool copy_initialization, const vector<Binding*>& constructors, bool has_user_declared_constructor, const vector<Expr>& template_order_args, Binding*& best, vector<int>& best_ranks, vector<Expr>& best_args, bool& ambiguous);
		bool use_hosted_allocator_constructor_fallback(TypePtr record, const vector<Expr>& args, Binding*& best, vector<Expr>& best_args, bool& ambiguous);
		Binding* instantiate_selected_constructor_body(Binding* best);
		Binding* wrap_inherited_constructor_if_needed(TypePtr record, Binding* best);
			bool hosted_vector_initializer_list_constructor(TypePtr record, Binding* ctor);
			void finalize_constructor_candidate(TypePtr record, Binding*& best);
			Binding* resolve_constructor_candidate(TypePtr type, const vector<Expr>& args, bool copy_initialization, vector<Expr>& converted);
			Expr make_constructor_init_expr(TypePtr type, const vector<Expr>& args, bool copy_initialization);
			Expr make_constructor_list_init_expr(TypePtr type, const Expr& init, bool copy_initialization);
			Expr make_call_expr(Expr callee, vector<Expr> args);
		bool make_member_pointer_call_expr(const Expr& callee, const vector<Expr>& args, Expr& out);
		bool make_record_callable_call_expr(const Expr& callee, const vector<Expr>& args, Expr& out);
		bool make_simple_builtin_call_expr(const Expr& callee, const vector<Expr>& args, Expr& out);
		bool make_direct_hosted_builtin_call_expr(const Expr& callee, const vector<Expr>& args, Expr& out);
		bool make_bit_count_builtin_call_expr(const Expr& callee, const vector<Expr>& args, Expr& out);
		bool make_atomic_builtin_call_expr(const Expr& callee, const vector<Expr>& args, Expr& out);
		bool make_bswap_builtin_call_expr(const Expr& callee, const vector<Expr>& args, Expr& out);
		void normalize_explicit_template_call_arguments(Expr& callee);
		bool call_is_dependent_template_call(const Expr& callee, const vector<Expr>& args);
		Binding* resolve_call_direct_binding(const Expr& callee, const vector<Expr>& args, vector<Expr>& converted);
		Expr finish_bound_call_expr(const Expr& callee, Binding* direct, const vector<Expr>& converted);
		Expr finish_indirect_call_expr(const Expr& callee, const vector<Expr>& args, vector<Expr>& converted);
		Expr make_builtin_va_arg_expr(Expr list, TypePtr result);
	Expr make_builtin_offsetof_expr(TypePtr record, const vector<string>& members);
		public:
			bool try_evaluate_constexpr_call(Binding* function, const vector<Node>& args, ConstexprValue& out);
			bool try_evaluate_constexpr_call_values(Binding* function, const vector<ConstexprValue>& args, ConstexprValue& out);
			bool try_evaluate_constexpr_constructor(Binding* function, TypePtr object_type, const vector<ConstexprValue>& args, ConstexprValue& out);
			bool try_evaluate_dependent_value_node(const Node& node, ConstexprValue& out);
			bool try_evaluate_constexpr_expr(const Node& node, ConstexprValue& out);
			bool try_evaluate_constexpr_binding(Binding* binding, ConstexprValue& out);
		private:
		void parse_pending_constexpr_function_bodies(Binding* function, bool ensure_extra);
		bool build_bodyless_constexpr_template_parameters(TemplateDeclaration* declaration, Binding* target, const vector<TemplateArgument>& arguments, vector<ParameterInfo>& parameters);
		bool replay_bodyless_constexpr_template(Binding* target);
		bool find_constexpr_function_body(Binding* function, Binding*& body_binding, map<Binding*, Node>::const_iterator& found);
		bool ensure_constexpr_function_body(Binding* function, Binding*& body_binding, map<Binding*, Node>::const_iterator& found);
		string dependent_value_expression_argument_cache_key(const TemplateArgument& arg);
		bool setup_dependent_value_expression_tokens(const TemplateArgument& arg, const string& cache_key, vector<Token>& save_tokens, vector<Token>& replay_tokens, bool& switched_tokens, size_t& parse_begin, size_t& parse_end);
		void evaluate_constexpr_template_expression(Expr& expr);
		bool evaluate_dependent_value_pack_expression(const TemplateArgument& arg, const Expr& expr, TemplateArgument& out);
		bool resolve_dependent_value_expression_argument(const TemplateArgument& arg, const Expr& expr, TemplateArgument& out);
		bool convert_dependent_value_expression_argument(const TemplateArgument& arg, Expr& expr, TemplateArgument& out);
		bool finish_dependent_value_expression_argument(const TemplateArgument& arg, Expr& expr, TemplateArgument& out);
		bool parse_dependent_value_expression_argument(const TemplateArgument& arg, size_t parse_begin, size_t parse_end, TemplateArgument& out);
		void apply_constexpr_value(Expr& expr, const ConstexprValue& value);
		Expr make_dependent_call_expr(const Expr& callee, const vector<Expr>& args);
		Expr make_id_expr(const QualifiedName& name);
		Expr make_template_substitution_id_expr(const QualifiedName& name);
		vector<Binding*> resolve_id_expr_bindings(const QualifiedName& name, map<Binding*, vector<TemplateArgument> >& explicit_template_arguments);
			Expr make_builtin_id_expr(const QualifiedName& name);
		void synthesize_default_assignment_lookup(const QualifiedName& name, vector<Binding*>& found);
		Expr make_missing_id_expr(const QualifiedName& name);
		Expr make_aliased_member_variable_id_expr(Binding* binding);
		Expr make_enumerator_id_expr(Binding* binding);
		void prefer_static_qualified_overloads(const QualifiedName& name, Expr& out, Binding*& binding);
			Expr make_implicit_member_id_expr(const QualifiedName& name, const vector<Binding*>& found, Binding* binding, Binding* this_binding, const map<Binding*, vector<TemplateArgument> >* explicit_template_arguments = NULL);
		Expr make_binary_expr(ETokenType op, const string& text, Expr lhs, Expr rhs);
		bool make_binary_pack_expr(ETokenType op, const string& text, const Expr& lhs, const Expr& rhs, Expr& out);
	bool make_builtin_converted_binary_expr(ETokenType op, const string& text, const Expr& lhs, const Expr& rhs, Expr& out);
	bool binary_candidate_accepts_operands(Binding* fn, const Expr& lhs, const Expr& rhs) const;
	vector<Binding*> binary_operator_candidates(ETokenType op, const string& text, const Expr& lhs, const Expr& rhs);
	void collect_associated_hidden_friends(TypePtr type, const string& name, set<Scope*>& seen, vector<Binding*>& out) const;
	void collect_associated_namespace_functions(TypePtr type, const string& name, set<Scope*>& seen, vector<Binding*>& out);
		Expr make_assignment_expr(ETokenType op, const string& text, Expr lhs, Expr rhs);
		Expr make_overloaded_compound_assignment_expr(ETokenType op, const string& text, Expr lhs, Expr rhs, TypePtr lhs_bare);
		Expr make_record_assignment_expr(Expr lhs, Expr rhs, TypePtr lhs_bare);
	Expr make_unary_expr(ETokenType op, const string& text, Expr inner);
	Expr make_postfix_expr(ETokenType op, const string& text, Expr inner);
	Expr make_subscript_expr(Expr lhs, Expr rhs);
	Expr make_record_subscript_expr(TypePtr record, Expr lhs, Expr rhs);
	Expr make_member_expr(Expr object, const string& name, const string& op);
		Expr make_dependent_member_expr(const Expr& object, const string& name, const string& op);
		Expr make_cast_expr(TypePtr target, const string& op_text, Expr inner, bool suppress_target_pack = false);
		bool make_cast_pack_expr(TypePtr target, const string& op_text, const Expr& inner, bool suppress_target_pack, Expr& out);
	Expr make_sizeof_expr(uint64_t value);
	Expr make_dependent_sizeof_expr(ETokenType keyword, TypePtr operand);
	Expr make_dependent_sizeof_pack_expr(const string& name);
	Expr make_address_expr(const string& text, Expr inner);
	Expr make_deref_expr(const string& text, Expr inner);
	bool is_assignment_operator(ETokenType& op) const;
	bool binary_operator(ETokenType& op, int& prec) const;
	bool expression_starts_type_name(TypePtr& type);
	bool is_zero_literal(const Expr& expr) const;
		bool type_can_bind_reference(TypePtr target, const Expr& expr) const;
		bool types_reference_compatible(TypePtr target, TypePtr source) const;
		bool pointer_conversion_viable(TypePtr source, TypePtr target) const;
		int record_base_distance(TypePtr source, TypePtr target) const;
		bool active_function_matches(Binding* function) const;
		bool active_context_has_class_access(Scope* class_scope) const;
		bool member_access_allowed(Binding* member, TypePtr object_record) const;
		bool is_pointer_arithmetic(const Expr& lhs, const Expr& rhs) const;
	bool is_pointer_difference(const Expr& lhs, const Expr& rhs) const;
			int scalar_conversion_rank(TypePtr source, TypePtr target) const;
			bool ranks_better(const vector<int>& lhs, const vector<int>& rhs) const;
			int explicit_template_argument_match_score(Binding* fn, const map<Binding*, vector<TemplateArgument> >& explicit_template_arguments) const;
			void ensure_copy_move_constructor_for_single_arg( TypePtr record, const vector<Expr>& args);
		void add_variadic_argument_ranks(Binding* fn, size_t arg_count, vector<int>& ranks) const;
		void prepare_member_call(Expr& callee, vector<Expr>& args);
		TypePtr pointer_arithmetic_type(ETokenType op, const Expr& lhs, const Expr& rhs) const;
	TypePtr pointee_type_for_member(TypePtr type) const;
	TypePtr expression_object_type(TypePtr type) const;
	TypePtr lvalue_to_rvalue_type(TypePtr type) const;
	TypePtr deduce_auto_return_type(Binding* function, const Expr& expr);
	TypePtr usual_arithmetic_type(TypePtr left, TypePtr right) const;
	ValueCategory call_category(TypePtr result) const;
	string value_category_name(ValueCategory category) const;
	string qualified_decl_name(const Binding* binding) const;
	string scoped_type_display_name(Scope* owner, const string& name) const;
	string class_tag(ETokenType key) const;
	string make_local_type_name(const string& prefix);
	string op_leaf(ETokenType type, const string& source) const;
	string operator_function_name(ETokenType type, const string& source) const;
	bool consume_explicit_specifier();
	void complete_static_member_initializer_replays(Node& node);
	void skip_balanced(ETokenType open, ETokenType close);
	void skip_template_parameter_clause();
};
void add_child(Node& parent, const Node& child);
void dump_node(ostream& out, const Node& node, int depth);
void annotate_expr_node(Expr& expr);
Expr make_integer_literal_expr(EFundamentalType type, uint64_t value);
Expr make_string_literal_expr(const string& value);
}  // namespace internal
}  // namespace pa12
